---
title: "Pieris virginiensis"
author: "Jeff Oliver"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r data-entry}
genus_name <- "Pieris"
species_name <- "virginiensis"
long_limits <- c(-99, -45)
lat_limits <- c(15, 70)

# Path to folder that contains retrieval script, get_clean_obs_function.R
retrieval_path <- "../insect_migration/scripts/"
retrieval_name <- "get_clean_obs_function.R"
```

```{r check-values, results = "asis", warning = FALSE}
# Keep track of whether a report can be assembled after the setup-check
continue_knitting <- TRUE

# Seems excessive...
if (file.exists("scripts/global_values.R")) {
  source(file = "scripts/global_values.R")
  globals <- global_values()
} else {
  cat("\n## Missing global values script\n")
  cat("Make sure scripts/global_values.R exists")
  continue_knitting <- FALSE
}

# Make sure retrieval_path has trailing /
if (substr(x = retrieval_path, start = nchar(retrieval_path), stop = nchar(retrieval_path)) != "/") {
  retrieval_path <- paste0(retrieval_path, "/")
}

# Check to make sure get_clean_obs_function exists
if (!file.exists(paste0(retrieval_path, retrieval_name))) {
  cat("\n## Missing required function `get_clean_obs_function`.\n")
  cat("Please check `retrieval_path` setting in `data-entry` chunk of Rmarkdown file. The function can be obtained from GitHub via `git clone https://github.com/keatonwilson/insect_migration.git`\n")
  continue_knitting <- FALSE
}

if ("FIXME" %in% c(species_name, genus_name)) {
  cat("\n## `FIXME` values need to be changed in `data-entry` chunk of Rmarkdown file.\n")
  continue_knitting <- FALSE
}

if (any(is.na(c(long_limits, lat_limits)))) {
  cat("\n## `NA` values need to be changed in `data-entry` chunk of Rmarkdown file.\n")
  continue_knitting <- FALSE
}

required_pkgs <- c("tidyverse", "spocc", "mapr")
missing_pkgs <- c()
for (pkg in required_pkgs) {
  if (!suppressPackageStartupMessages(library(package = pkg, logical.return = TRUE, character.only = TRUE))) {
    missing_pkgs <- c(missing_pkgs, pkg)
  }
}
if (length(missing_pkgs) > 0) { 
  cat("\n## Missing one or more required libraries.\n")
  cat("Please install the following package(s): ", paste(missing_pkgs, collapse = ", "), ".\n", sep = "")
  continue_knitting <- FALSE
}
```

```{r status-check-setup}
# If there are problems at this point, don't bother evaluating the rest of the 
# document
if (!continue_knitting) {
  knitr::knit_exit()
}
```

# Report for _`r paste(genus_name, species_name, sep = " ")`_

```{r download-data, include = FALSE}
# Use include = FALSE to suppress warning messages
source(file = paste0(retrieval_path, retrieval_name))

data_file <- paste0("data/", genus_name, "-", species_name, "-spocc.csv")

if (file.exists(data_file)) {
  observations <- read_csv(file = data_file)
} else {
  observations <- get_clean_obs(genus = genus_name, 
                                species = species_name, 
                                lonlim = long_limits, 
                                latlim = lat_limits)
# UPDATE: This error is likely caused by local network issues causing long 
# address resolution leading to timeouts
# TODO: need to test this with get_clean_obs_function; the above throws:
# Quitting from lines 87-92 (Pieris-virginiensis-emergence.Rmd) 
#  Error: object 'longitude' not found
# the error happens somewhere around:
# mutate_impl(.data, dots, caller_env()) 
# mutate.tbl_df(., longitude = as.numeric(longitude), latitude = as.numeric(latitude)) 
# mutate(., longitude = as.numeric(longitude), latitude = as.numeric(latitude)) 

}

if (nrow(observations) > 0) {
  write_csv(x = observations, path = data_file)
} else {
  cat("\n## No records returned for _", genus_name, " ", species_name, "_.\n")
  cat("Check to be sure names are spelled correctly and iNat and GBIF servers are responsive")
  continue_knitting <- FALSE
}
```

```{r status-check-data}
# If there are problems at this point, don't bother evaluating the rest of the 
# document
if (!continue_knitting) {
  knitr::knit_exit()
}
```

Retrieval from iNaturalist and GBIF returned `r nrow(observations)` observations.

```{r data-cleaning}
# Restrict to the days and years of interest
observations <- observations %>%
  filter(!is.na(date),
         yday(x = date) >= globals$min_julian,
         yday(x = date) <= globals$max_julian,
         year(x = date) >= globals$min_year,
         year(x = date) <= globals$max_year)

if (nrow(observations) == 0) {
  cat("\n## Zero observations remain after date filtering.\n")
  cat("Current filters only include ", globals$min_year, "-", globals$max_year)
  cat(" and julian days ", globals$min_julian, "-", globals$max_julian, ".\n")
}
```

```{r status-check-cleaning}
# If there are problems at this point, don't bother evaluating the rest of the 
# document
if (!continue_knitting) {
  knitr::knit_exit()
}
```
